"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Menu, X, UserCircle } from "lucide-react";
import { useState } from "react";
import { useApp } from "@/components/app-provider";

export function Navbar() {
  const [open, setOpen] = useState(false); const pathname = usePathname(); const { user } = useApp();
  const links = [{ href: "/search", label: "Find accommodation" }, { href: "/how-it-works", label: "How it works" }, { href: "/saved", label: "Saved" }];
  return <header className="border-b border-[#e9e7e2] bg-[var(--cream)]"><div className="container flex h-[74px] items-center justify-between"><Link href="/" className="flex items-center gap-2 text-xl font-black tracking-[-.04em] text-[var(--navy)]"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[var(--orange)] text-sm text-white">C</span>CampusStay</Link><nav className="hidden items-center gap-8 md:flex">{links.map((link) => <Link key={link.href} href={link.href} className={`text-sm font-semibold ${pathname === link.href ? "text-[var(--orange)]" : "text-[#53616a] hover:text-[var(--navy)]"}`}>{link.label}</Link>)}{user && <Link href="/dashboard" className="text-sm font-semibold text-[#53616a] hover:text-[var(--navy)]">Dashboard</Link>}</nav><div className="hidden items-center gap-2 md:flex">{user ? <Link href="/profile" className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold text-[var(--navy)] hover:bg-white"><UserCircle size={20} />{user.name.split(" ")[0]}</Link> : <><Link href="/login" className="rounded-lg px-3 py-2 text-sm font-bold text-[var(--navy)] hover:bg-white">Log in</Link><Link href="/signup" className="rounded-lg bg-[var(--navy)] px-4 py-2.5 text-sm font-bold text-white hover:bg-[#1d4666]">Sign up</Link></>}</div><button className="focus-ring rounded-lg p-2 text-[var(--navy)] md:hidden" onClick={() => setOpen(!open)} aria-label={open ? "Close menu" : "Open menu"}>{open ? <X /> : <Menu />}</button></div>{open && <div className="border-t border-[#e9e7e2] bg-white px-5 pb-5 md:hidden"><nav className="container flex flex-col gap-1 pt-3">{links.concat(user ? [{ href: "/dashboard", label: "Dashboard" }] : []).map((link) => <Link key={link.href} onClick={() => setOpen(false)} href={link.href} className="rounded-lg px-3 py-3 text-sm font-bold text-[var(--navy)] hover:bg-[var(--cream)]">{link.label}</Link>)}{user ? <Link href="/profile" onClick={() => setOpen(false)} className="mt-2 rounded-lg bg-[var(--navy)] px-3 py-3 text-center text-sm font-bold text-white">View profile</Link> : <div className="mt-2 grid grid-cols-2 gap-2"><Link href="/login" onClick={() => setOpen(false)} className="rounded-lg border border-[#d9dfe0] px-3 py-3 text-center text-sm font-bold text-[var(--navy)]">Log in</Link><Link href="/signup" onClick={() => setOpen(false)} className="rounded-lg bg-[var(--orange)] px-3 py-3 text-center text-sm font-bold text-white">Sign up</Link></div>}</nav></div>}</header>;
}
