"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Mail } from "lucide-react";
import { FormEvent, useState } from "react";
import { Button } from "@/components/button";
import { useApp } from "@/components/app-provider";

export default function LoginPage() { const router = useRouter(); const { signIn } = useApp(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const submit = (event: FormEvent) => { event.preventDefault(); if (!email.includes("@") || password.length < 6) { setError("Enter a valid email and a password with at least 6 characters."); return; } signIn({ name: email.split("@")[0], email }); router.push("/dashboard"); }; return <main className="container flex min-h-[650px] items-center justify-center py-16"><div className="w-full max-w-md"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#697580]"><ArrowLeft size={16} />Back to home</Link><div className="mt-8 rounded-xl border border-[#e3e4df] bg-white p-7 shadow-soft md:p-9"><p className="eyebrow">Welcome back</p><h1 className="mt-3 text-3xl font-black tracking-[-.04em] text-[var(--navy)]">Log in to CampusStay</h1><p className="mt-3 text-sm leading-6 text-[#697580]">Keep your favourite homes and accommodation requests together.</p><form onSubmit={submit} className="mt-7 grid gap-4"><label className="grid gap-2 text-sm font-bold text-[var(--navy)]">Email address<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} className="focus-ring min-h-12 rounded-lg border border-[#dfe3df] px-3 font-normal outline-none" placeholder="you@example.com" /></label><label className="grid gap-2 text-sm font-bold text-[var(--navy)]">Password<input type="password" required value={password} onChange={(e) => setPassword(e.target.value)} className="focus-ring min-h-12 rounded-lg border border-[#dfe3df] px-3 font-normal outline-none" placeholder="Your password" /></label><div className="flex justify-end"><button type="button" className="text-xs font-bold text-[var(--orange)]">Forgot password?</button></div>{error && <p className="rounded-lg bg-[#fff0e8] px-3 py-2 text-sm text-[#a84712]">{error}</p>}<Button type="submit">Log in</Button></form><div className="my-6 flex items-center gap-3 text-xs text-[#9aa3a6]"><span className="h-px flex-1 bg-[#e3e4df]" />OR<span className="h-px flex-1 bg-[#e3e4df]" /></div><button className="flex min-h-11 w-full items-center justify-center gap-2 rounded-lg border border-[#dfe3df] text-sm font-bold text-[var(--navy)] hover:bg-[var(--cream)]"><Mail size={17} />Continue with Google</button><p className="mt-7 text-center text-sm text-[#697580]">Don&apos;t have an account? <Link href="/signup" className="font-bold text-[var(--orange)]">Sign up</Link></p></div></div></main>; }
