"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Mail } from "lucide-react";
import { FormEvent, useState } from "react";
import { Button } from "@/components/button";
import { useApp } from "@/components/app-provider";

export default function SignupPage() { const router = useRouter(); const { signIn } = useApp(); const [form, setForm] = useState({ name: "", email: "", password: "", confirm: "" }); const [error, setError] = useState(""); const submit = (event: FormEvent) => { event.preventDefault(); if (form.name.trim().length < 2) return setError("Please enter your full name."); if (!form.email.includes("@")) return setError("Please enter a valid email address."); if (form.password.length < 6) return setError("Your password should be at least 6 characters."); if (form.password !== form.confirm) return setError("Your passwords do not match."); signIn({ name: form.name, email: form.email }); router.push("/dashboard"); }; const input = (key: keyof typeof form, label: string, type = "text") => <label className="grid gap-2 text-sm font-bold text-[var(--navy)]">{label}<input type={type} required value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="focus-ring min-h-12 rounded-lg border border-[#dfe3df] px-3 font-normal outline-none" /></label>; return <main className="container flex min-h-[700px] items-center justify-center py-16"><div className="w-full max-w-md"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#697580]"><ArrowLeft size={16} />Back to home</Link><div className="mt-8 rounded-xl border border-[#e3e4df] bg-white p-7 shadow-soft md:p-9"><p className="eyebrow">Make the search yours</p><h1 className="mt-3 text-3xl font-black tracking-[-.04em] text-[var(--navy)]">Create your account</h1><p className="mt-3 text-sm leading-6 text-[#697580]">Save places, manage requests and pick up your search anytime.</p><form onSubmit={submit} className="mt-7 grid gap-4">{input("name", "Full name")}{input("email", "Email address", "email")}{input("password", "Password", "password")}{input("confirm", "Confirm password", "password")}{error && <p className="rounded-lg bg-[#fff0e8] px-3 py-2 text-sm text-[#a84712]">{error}</p>}<Button type="submit">Create account</Button></form><div className="my-6 flex items-center gap-3 text-xs text-[#9aa3a6]"><span className="h-px flex-1 bg-[#e3e4df]" />OR<span className="h-px flex-1 bg-[#e3e4df]" /></div><button className="flex min-h-11 w-full items-center justify-center gap-2 rounded-lg border border-[#dfe3df] text-sm font-bold text-[var(--navy)] hover:bg-[var(--cream)]"><Mail size={17} />Continue with Google</button><p className="mt-7 text-center text-sm text-[#697580]">Already have an account? <Link href="/login" className="font-bold text-[var(--orange)]">Log in</Link></p></div></div></main>; }
